// app/layout.js
import { Inter } from 'next/font/google'
import './globals.css' // Import Tailwind CSS

const inter = Inter({ 
  subsets: ['latin'],
  weight: ['500', '600', '700'] 
})

export const metadata = {
  title: "Your App Title",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  )
}